# Generated by Django 4.2 on 2024-02-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_post_options_post_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0002_order_orderitem_paydaddress_delete_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Pay_address',
        ),
        migrations.DeleteModel(
            name='PaydAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.payedaddress'),
        ),
    ]
